### ISSUE TITLE
Mapeamento para o Relacional

### ISSUE THREAD

**Issue by GabrielCavalcanti13** [GabrielCavalcanti13/gymCad#1]
Passar o diagrama ER para o Modelo Relacional

**Comment by GabrielCavalcanti13** [comment]
Começar após a prova de ES e terminar até dia 10/04/2019 (Quarta-feira)

**Comment by aplneto** [comment]
[Diagrama](https://github.com/GabrielCavalcanti13/projeto_BD/blob/master/Entregas/1%C2%AA%20entrega/1%C2%AA%20entrega%20-%20Modelo%20ER.brM3)

**Comment by aplneto** [comment]
[MySQL Workbench](https://dev.mysql.com/downloads/workbench/5.2.html)
Sugestão de ferramenta para construção do modelo e scripts (ver #2)

**Comment by prgsouza** [comment]
lembrar de normalizar até a bcnf
